apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore

resources:
  - postgres-cluster.yaml
  - redis.yaml
  - elasticsearch.yaml

commonLabels:
  app.kubernetes.io/part-of: bookstore
  app.kubernetes.io/managed-by: kustomize
